language: python

notifications:
  email:
    on_success: never

cache:
  directories:
    - $HOME/.cache/pip

matrix:
  include:
    - python: 3.6
    - python: 3.6
      env: TEST_MODE=PEP8

install:
  - "pip install flake8"

script:
  - "flake8 ."

after_success:
  - coveralls
